//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dale.Utils.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceGeneral {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceGeneral() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dale.Utils.Resources.ResourceGeneral", typeof(ResourceGeneral).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se ha cancelado con éxito..
        /// </summary>
        public static string CancelNOK {
            get {
                return ResourceManager.GetString("CancelNOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se ha cancelado con éxito..
        /// </summary>
        public static string CancelOK {
            get {
                return ResourceManager.GetString("CancelOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se ha eliminado con éxito..
        /// </summary>
        public static string DeleteNOK {
            get {
                return ResourceManager.GetString("DeleteNOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se ha eliminado con éxito..
        /// </summary>
        public static string DeleteOK {
            get {
                return ResourceManager.GetString("DeleteOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se ha insertado con éxito, valide sus datos..
        /// </summary>
        public static string InsertNOK {
            get {
                return ResourceManager.GetString("InsertNOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se ha insertado con éxito..
        /// </summary>
        public static string InsertOK {
            get {
                return ResourceManager.GetString("InsertOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La consulta no genera datos..
        /// </summary>
        public static string QueryNOK {
            get {
                return ResourceManager.GetString("QueryNOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No hay registros con los criterios seleccionados..
        /// </summary>
        public static string ReportNoData {
            get {
                return ResourceManager.GetString("ReportNoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se ha podido generar el reporte con éxito..
        /// </summary>
        public static string ReportNOK {
            get {
                return ResourceManager.GetString("ReportNOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El reporte ha sido generado con éxito..
        /// </summary>
        public static string ReportOK {
            get {
                return ResourceManager.GetString("ReportOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se ha actualizado con éxito..
        /// </summary>
        public static string UpdateNOK {
            get {
                return ResourceManager.GetString("UpdateNOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se ha actualizado con éxito..
        /// </summary>
        public static string UpdateOK {
            get {
                return ResourceManager.GetString("UpdateOK", resourceCulture);
            }
        }
    }
}
